[build]
  builder = "heroku/builder:22"

[build.args]
  # Dockerfile path relative to server/
  
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50

  [[services.http_checks]]
    interval = 15000
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
